"""
static_messages.py — Retained message constants.

Contains ONLY:
  - System-level fallback strings (LLM unavailable / hard error)
  - Escalation and reliability-critical strings delivered outside the LLM path

Do NOT add conversational prompts, retry phrases, or slot-ask strings here.
Those belong in agent prompts and are generated by the LLM via WorkerResult.response.
"""

from __future__ import annotations

# ── System fallback (used only when an unhandled exception fires) ─────────────
MSG_EMERGENCY = "Technical issue. Reference: {ref}."

# ── Guard escalation — legal / safety critical; must never drift ──────────────
MSG_TRANSFER_REQUEST = [
    "No problem. Let me connect you to one of our live representatives. Please hold.",
    "Of course. I'll transfer you to a specialist right away. Please hold.",
]

# Honest escalation after a caller's request was declined/deflected twice —
# never repeat the same re-ask a third time (Phase 4 ignored-request guard).
MSG_REPEATED_REQUEST_ESCALATE = [
    (
        "I hear you — I haven't been able to take care of that for you, "
        "so let me connect you with a representative who can. Please hold."
    ),
    (
        "You've asked about that a couple of times and I can't handle it on this call — "
        "I'm transferring you to a representative who can help. Please hold."
    ),
]
MSG_OFFTOPIC_GLOBAL = [
    "I can help with provider services or claims — is that what you're calling about today?",
    "Happy to help with provider services or claims. What can I do for you?",
    (
        "I'm set up to help with provider services or claims.\n"
        "Is there something along those lines I can help with?"
    ),
]
MSG_ABUSE_ESCALATION = [
    "I'm going to connect you with a live representative who can further assist you. Please hold.",
    "Let me transfer you to a member of our team who can help. Please hold.",
]
MSG_SELF_HARM_ESCALATION = [
    (
        "I hear you, and I want to make sure you get the right support. "
        "I'm connecting you with someone who can help right now. Please stay on the line."
    ),
    (
        "Thank you for sharing that with me. I want to connect you with someone "
        "who is better placed to help. Please hold — I'm transferring you now."
    ),
]


# ── WAIT acknowledgements — static-only by design (zero generation-LLM calls);
#    delivered from the WAIT branch in _collect_slot (core/slot_manager.py) ────
MSG_WAIT_ACK = [
    "Of course — take your time.",
    "No rush, take your time. I'm here when you're ready.",
    "Sure, take all the time you need.",
]
MSG_WAIT_NUDGE = [
    "No problem — whenever you're ready, I still need your {slot_label}.",
]


# ── Slot exhaustion — legal; max-retry escalation must fire reliably ──────────
def build_slot_exhausted_message(slot_name: str = "") -> str:
    """Return a warm, slot-aware escalation message for retry exhaustion."""
    if slot_name:
        label = slot_name.replace("_", " ").strip()
        return (
            f"I wasn't able to capture your {label} after a few tries. "
            f"Let me connect you with a representative who can help."
        )
    return (
        "I wasn't able to capture that information after a few tries. "
        "Let me connect you with a representative who can help."
    )
